name: Bálázóka
version: '${project.version}'
main: dev.tf2levi.balazo.Balazoka
api-version: 1.18
authors: [ Levi ]
description: Lehetővé teszi hogy egy gép automatikusan learasson és a búzát bálába szedje, illetve a magot különszelektálja.
website: https://www.dieselhungary.hu
