name: Balazoka
version: '${project.version}'
main: dev.tf2levi.balazo.Balazoka
api-version: 1.18
authors: [ Levi ]
description: Lehetővé teszi hogy egy gép automatikusan learasson és a búzát bálába szedje, illetve a magot különszelektálja.
website: https://www.dieselhungary.hu
commands:
  balazo:
    description: Fő parancs. Az argumentumoknak külön jogaik vannak.
    permission: balazo.use
    aliases: [ harvester, balazoka ]
    usage: /<command> [args]
permissions:
  balazo.use:
    default: op
    description: Az a jog amivel e segítség menü már megjeleníthető.
