name: HarvestMachine
version: '${project.version}'
main: dev.tf2levi.balazo.Balazoka
api-version: 1.18
authors: [ Levi ]
description: Termények automatikus összeszedésére és a bejövő termés szelektálására alkalmas.
website: https://www.dieselhungary.hu
commands:
  balazo:
    description: Fő parancs. Az argumentumoknak külön jogaik vannak.
    permission: hmachine.use
    aliases: [ harvester, balazoka ]
    usage: /<command> [args]
permissions:
  balazo.use:
    default: op
    description: Az a jog amivel e segítség menü már megjeleníthető.
